### Getting the Employee details
# Get Employee Details
# GET http://localhost:4004/EmployeeSRV/Employee HTTP/1.1

# Get Employee Details along with address
GET http://localhost:4004/EmployeeSRV/Employee?$expand=address HTTP/1.1

# Delete the particular employee using Employee ID
# DELETE http://localhost:4004/EmployeeSRV/Employee/bd26b2ab-6387-4e99-904f-ad728fa911e4 HTTP/1.1

